### PR TITLE
Add jest-webdriver project

### PR DESCRIPTION
**Pull request by alexeyraspopov**
I hope that's the right place to mention the project.

### CODE REVIEW

**Comment by SimenB** [comment]
Maybe a new section for custom environments?

**Comment by alexeyraspopov** [comment]
@SimenB, makes sense, give me a second to update

**Comment by orta** [comment]
👍

**Comment by alexeyraspopov** [comment]
@SimenB, I guess it worth squashing, so to keep things in one commit.

**Comment by orta** [comment]
Heh, I'm less worried about that, I can't really see a reason for people caring about the history of this repo

**Comment by alexeyraspopov** [comment]
@orta, ok then. Thanks!

**Pull request merged**
