### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jehy**
Added jest-dot-reporter to a list of reporters and improved simple dot reporter description.

### CODE REVIEW

**Comment by connectdotz** [comment]
Indeed, it does sound a bit confusing, ping the repo owners (@jodonnell  @pierreroth64) to chime in their opinions...

**Comment by jodonnell** [comment]
lol, yeah definitely kind of confusing.  the main reason i have my dot reporter as simple as it is, is things that update like that don't render well in an emacs shell.

**Comment by jehy** [comment]
Both reporters are great, I think that it would be good to rename one of them.
@pierreroth64, what about something like `jest-progress-bar-reporter`?

**Comment by pierreroth64** [comment]
Hi, sorry for the delayed response. It's ok for me to rename it to `jest-progress-bar-reporter`. I will add a deprecation message to existing `jest-dot-reporter`. I expect to work on it by the end of this week.

**Comment by pierreroth64** [comment]
✅ Done:
- deprecated: https://www.npmjs.com/package/jest-dot-reporter
- new one: https://www.npmjs.com/package/jest-progress-bar-reporter

**Comment by jodonnell** [comment]
And should i rename mine to jest-dot-reporter now?

**Comment by jehy** [comment]
PR updated according to changes : )

**Comment by connectdotz** [comment]
it looks good from the documentation perspective, but I haven't used them personally, not sure if it is the reviewers' responsibility to vet the feature/security/quality of these packages...? cc @SimenB for guidance...

**Pull request merged**
