### PR TITLE
Add popular packages/resources

### PR DESCRIPTION
**Pull request by mattphillips**
Add:
- [jest-enzyme](https://github.com/FormidableLabs/enzyme-matchers/tree/master/packages/jest-enzyme)
- [enzyme-to-json](https://github.com/adriantoine/enzyme-to-json)
- [React Jest workshop](https://github.com/kentcdodds/react-jest-workshop).
 - [jest-styled-components](https://github.com/styled-components/jest-styled-components)

I wasn't sure which categories the following should go under?
 - [vue-jest](https://github.com/vuejs/vue-jest)
 - [storyshots](https://github.com/storybooks/storybook/tree/master/addons/storyshots)

### CODE REVIEW

**Comment by orta** [comment]
Maybe there could be a category about extending other environments to its jest?

**Comment by SimenB** [comment]
ts-jest as well, wherever vue-jest ends up

**Comment by thymikee** [comment]
Ah, I forgot about Angular integration! 😅  [jest-preset-angular](https://github.com/thymikee/jest-preset-angular). We should fit it somewhere

**Comment by orta** [comment]
OK, this looks good to me 👍 

The other ones discussed can come in on another PR

**Comment by mattphillips** [comment]
Nice one @orta been busy and forgot about this 😆

**Pull request merged**
