### PR TITLE
Add github-actions-jest-reporter package

### PR DESCRIPTION
**Pull request by MatteoH2O1999**
Add the github-actions-jest-reporter package. This package emulates jest default one but uses Github Actions groups for logging, thus folding passed test and leaving failed ones spread out to show at first glance what went wrong but preserving all the details.

### CODE REVIEW

**Comment by SimenB** [comment]
This is awesome! I think that should be the default behaviour in Jesta s well - would you be up for sending a PR?

/cc @mrazauskas

**Comment by mrazauskas** [comment]
Can't agree more, it would be really nice to have this behaviour in Jest. Should be easy to implement, if it is possible to avoid `@actions/core` dependency.

**Comment by SimenB** [comment]
Seems straight forward: https://github.com/actions/toolkit/blob/819157bf872a49cfcc085190da73894e7091c83c/packages/core/src/core.ts#L301-L317

**Comment by MatteoH2O1999** [comment]
The problem with that would be that you would have to pay attention to any change to the Github runner software. Depending on `@actions/core` allows to abstract from that.
If I were to add this to Jest, I would add `github-actions-jest-reporter` as a dependency and use the exported reporter instead of the default one if verbose is false and GITHUB_ACTIONS is in the environment.
If you agree with that, let me know so I can open a PR, otherwise I am of course open to your suggestions

**Pull request merged**
