### PR TITLE
Add jest-a-coverage-slip-detector

### PR DESCRIPTION
**Pull request by jcw-**
Adds the `jest-a-coverage-slip-detector` package to the Coverage category. One of the unique capabilities from the other two in that category is that it supports parallelized CI runs, with automatic merging of coverage.

### CODE REVIEW

**Review by mrazauskas — APPROVED** [review]
Thanks!

**Comment by SimenB** [comment]
Very cool @jcw- 👍 

Since you mentioned parallelized runs - does that work properly with [`--shard`](https://jestjs.io/docs/cli#--shard)?

**Comment by jcw-** [comment]
> Very cool @jcw- 👍
> 
> Since you mentioned parallelized runs - does that work properly with [`--shard`](https://jestjs.io/docs/cli#--shard)?

@SimenB Yep, that should inherently be supported! However you split up your tests, this will merge the coverage generated from each run/shard (as a follow-up step in your workflow). The [documentation for this](https://github.com/GetJobber/jest-a-coverage-slip-detector#concurrency-and-parallelism) uses CircleCI's utility `circleci tests split --split-by=timings` as an example, but `--shard` would be similar (more like the --split-by=name equivalent though probably).

**Comment by jcw-** [comment]
@SimenB fyi - I'm also covering this library as part of an article on [Building Test Coverage Momentum ](https://dev.to/jobber/building-test-coverage-momentum-1gh7)that just went live today :)

**Pull request merged**
